MOAI-879 (DIRS Rules updates)
mn-mde-edfi/Validation pull request #129
Opened 2022-09-23 20:16 UTC by mpartha-dl

Created DIRS Rules 57.01.0001 and 57.01.0002

2022-09-26 22:38 UTC, mmarable-dlp approved these changes

2022-10-28 05:41 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.01.0001.sql
> +	@RuleValidationId, SchoolId, @RuleId RuleId, @IsError IsError, @Message [Message]
I wouldn't use Schoolid here - you have better options - StudentUniqueId is probably the best option.  So you'll have to update the select to pull the studentuniqueid.

Also I would include additional data in the message - like the incident identifier, the weapon descriptor **code value**, and the school id.

2022-10-28 05:43 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.01.0002.sql
> +	@RuleValidationId, SchoolId, @RuleId RuleId, @IsError IsError, @Message [Message]
Again - here you should use the studentuniqueid.  Whenever your rule can be related to a student - you'll want to insert the studentuniqueid in the rulevalidationdetail.Id column.
You should also provide additional info to help the user in the message such as the Incident Identifier and the schoolid.

2022-10-28 05:44 UTC, steve-dlp requested changes
see comments @mpartha-dl

2022-12-21 17:09 UTC, steve-dlp commented
These rules need a @districtid filter 
@mmarable-dlp can you adjust please?

2023-01-17 18:45 UTC, mmarable-dlp approved these changes

2023-01-18 19:15 UTC, steve-dlp approved these changes

2023-01-18 19:15 UTC, merged