Create 57.04.0001.sql
mn-mde-edfi/Validation pull request #154
Opened 2023-02-01 00:07 UTC by steve-dlp

new rule

2023-02-01 20:22 UTC, ckimdbl requested changes
please refer to comments I've left for changes.

2023-02-01 20:22 UTC, ckimdbl commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.03.0009.sql
> +  sdiba.StudentUniqueId,
needs to join to edfi.Student to get StudentUniqueId

2023-02-01 20:22 UTC, ckimdbl commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0002.sql
> +  )
extra )

2023-02-01 20:22 UTC, ckimdbl commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0003.sql
> +DECLARE @Message NVARCHAR(MAX) = 'EstimatedStudentsEnrolled is required if NonOffender Type  =  4 MARSS information unknown and EstimatedStudentsNotEnrolled = 0 ;
missing closing '

2023-02-01 20:22 UTC, ckimdbl commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0004.sql
> +DECLARE @Message NVARCHAR(MAX) = 'EstimatedStudentsNotEnrolled is required if NonOffender Type  =  4 MARSS information unknown and EstimatedStudentsEnrolled = 0 ;
missing closing '

2023-02-01 20:22 UTC, ckimdbl commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0007.sql
> +SELECT	@RuleValidationId, StudentUniqueId, @RuleId RuleId, @IsError IsError, @Message  + ' , IncidentIdentifier: ' + cast(IncidentIdentifier as varchar) + ', DidInjuryOccur: ' + cast(DidInjuryOccur a
StudentUniqueId not included in the failed_rows CTE

2023-02-06 16:52 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.03.0009.sql
> +  sdiba.StudentUniqueId,
Updated

2023-02-06 16:54 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0002.sql
> +  )
updated

2023-02-06 16:57 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0004.sql
> +DECLARE @Message NVARCHAR(MAX) = 'EstimatedStudentsNotEnrolled is required if NonOffender Type  =  4 MARSS information unknown and EstimatedStudentsEnrolled = 0 ;
updated

2023-02-06 16:59 UTC, steve-dlp commented on ValidationWeb/Content/SqlRules/DIRSRuleSet/dirs-rule-57.05.0007.sql
> +SELECT	@RuleValidationId, StudentUniqueId, @RuleId RuleId, @IsError IsError, @Message  + ' , IncidentIdentifier: ' + cast(IncidentIdentifier as varchar) + ', DidInjuryOccur: ' + cast(DidInjuryOccur a
Updated to use Schoolid since anonymous offender has no studentid

2023-02-15 05:01 UTC, merged